# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default='tenders@codingdojo.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
