# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171109_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default='xyz@amazon.com'),
            preserve_default=False,
        ),
    ]
