# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='A Dojo'),
            preserve_default=False,
        ),
    ]
